
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 22:00:19 GMT-03:00 2018
//----------------------------------------------------

package br.com.minic.analisadorsintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 31;
  public static final int CHAR = 4;
  public static final int SOMA = 28;
  public static final int ABRE_CHAVE = 33;
  public static final int LITERAL_PONTO_FLUTUANTE = 18;
  public static final int DIFERENTE = 27;
  public static final int DOUBLE = 6;
  public static final int FECHA_CHAVE = 34;
  public static final int LETRA_H = 40;
  public static final int INT = 3;
  public static final int NEGACAO = 41;
  public static final int PONTO = 38;
  public static final int VIRGULA = 32;
  public static final int IDENTIFICADOR = 16;
  public static final int IGUAL = 26;
  public static final int PRINTSTR = 13;
  public static final int DIV = 30;
  public static final int MAIN = 7;
  public static final int IF = 9;
  public static final int PRINTINT = 12;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int PONTO_VIRGULA = 39;
  public static final int ABRE_PARENTESES = 35;
  public static final int MAIOR = 23;
  public static final int error = 1;
  public static final int INCLUDE = 2;
  public static final int LITERAL_CHAR = 19;
  public static final int MENOR = 21;
  public static final int VOID = 15;
  public static final int LITERAL_INTEIRO = 17;
  public static final int JOGO_DA_VELHA = 37;
  public static final int PRINTF = 11;
  public static final int ELSE = 14;
  public static final int LITERAL_STRING = 20;
  public static final int WHILE = 10;
  public static final int FECHA_PARENTESES = 36;
  public static final int FLOAT = 5;
  public static final int ATRIBUICAO = 25;
  public static final int MENOR_IGUAL = 22;
  public static final int SUB = 29;
  public static final int MAIOR_IGUAL = 24;
}

